version: '2'
services:
  Desktop-1:
    environment:
    - PASSWORD=passwordpass123
    - USER=jay
    cap_add:
    - SYS_PTRACE
    shm_size: 1g
    image: spamtram10/nomachine
    stdin_open: true
    tty: true
    ports:
    - 4000:4000/tcp
